

# AAPT, TODO
PRODUCT_AAPT_CONFIG      := normal
PRODUCT_AAPT_PREF_CONFIG := xhdpi

# Boot animation
TARGET_SCREEN_HEIGHT := 1920
TARGET_SCREEN_WIDTH  := 1200

# Treble
PRODUCT_USE_VNDK_OVERRIDE := true

# it's a tablet
PRODUCT_CHARACTERISTICS  := tablet
